// Files of src/content/products/<slug>/assets/ (icon.svg + images generated by "npm run og"),
// published at /<slug>/assets/<file>. Build-time only (Node).
import fs from 'node:fs';
import path from 'node:path';
import { URLS, type Product } from './model.ts';

const dirOf = (slug: string) => path.resolve('src/content/products', slug, 'assets');

export const assetFiles = (slug: string) => {
  const dir = dirOf(slug);
  return fs.existsSync(dir) ? fs.readdirSync(dir).filter((f) => !f.startsWith('.')) : [];
};
export const readAsset = (slug: string, file: string) => fs.readFileSync(path.join(dirOf(slug), file));

// Share image of a product page: og-<lang>.png, else the default language's, else og.png.
export function ogImage(p: Product, loc: string) {
  const files = assetFiles(p.slug);
  for (const f of [`og-${loc}.png`, `og-${p.def}.png`, 'og.png']) if (files.includes(f)) return URLS.abs(`${p.basePath}assets/${f}`);
  return null;
}

export const hasAsset = (p: Product, file: string) => assetFiles(p.slug).includes(file);
